import { addDays, addHours } from "date-fns";
import type {
  Contact,
  ContactNote,
  ReminderWithRelations,
} from "@/lib/types/database";

const now = new Date();

export const demoContacts: Contact[] = [
  {
    id: "demo-1",
    user_id: "demo",
    google_resource_name: "people/demo-1",
    display_name: "Jordan Lee",
    given_name: "Jordan",
    family_name: "Lee",
    emails: ["jordan.lee@example.com"],
    phones: ["+1 555-0101"],
    photo_url: null,
    birthday_month: 8,
    birthday_day: 28,
    birthday_year: null,
    anniversary_month: null,
    anniversary_day: null,
    anniversary_year: null,
    raw: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "demo-2",
    user_id: "demo",
    google_resource_name: "people/demo-2",
    display_name: "Sam Rivera",
    given_name: "Sam",
    family_name: "Rivera",
    emails: ["sam.rivera@example.com"],
    phones: [],
    photo_url: null,
    birthday_month: 3,
    birthday_day: 12,
    birthday_year: 1990,
    anniversary_month: 6,
    anniversary_day: 15,
    anniversary_year: 2018,
    raw: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "demo-3",
    user_id: "demo",
    google_resource_name: "people/demo-3",
    display_name: "Alex Chen",
    given_name: "Alex",
    family_name: "Chen",
    emails: ["alex.chen@example.com"],
    phones: ["+1 555-0199"],
    photo_url: null,
    birthday_month: null,
    birthday_day: null,
    birthday_year: null,
    anniversary_month: null,
    anniversary_day: null,
    anniversary_year: null,
    raw: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
];

export const demoNotes: ContactNote[] = [
  {
    id: "note-1",
    user_id: "demo",
    contact_id: "demo-1",
    body: "Ask about the new apartment — they mentioned moving in September.",
    tags: [],
    remind_at: addDays(now, 2).toISOString(),
    created_at: addDays(now, -5).toISOString(),
    updated_at: addDays(now, -5).toISOString(),
  },
  {
    id: "note-2",
    user_id: "demo",
    contact_id: "demo-1",
    body: "Loves hiking. Last trip was Yosemite.",
    tags: ["interests"],
    remind_at: null,
    created_at: addDays(now, -30).toISOString(),
    updated_at: addDays(now, -30).toISOString(),
  },
  {
    id: "note-3",
    user_id: "demo",
    contact_id: "demo-2",
    body: "Starting a new job at Acme Corp next month.",
    tags: [],
    remind_at: null,
    created_at: addDays(now, -3).toISOString(),
    updated_at: addDays(now, -3).toISOString(),
  },
];

export const demoReminders: ReminderWithRelations[] = [
  {
    id: "rem-1",
    user_id: "demo",
    type: "pre_event",
    status: "pending",
    due_at: addHours(now, 3).toISOString(),
    title: "Before Coffee with Jordan Lee",
    body: "• Ask about the new apartment — they mentioned moving in September.\n• Loves hiking. Last trip was Yosemite.",
    contact_id: "demo-1",
    note_id: "note-1",
    event_id: null,
    dedupe_key: "demo-pre-1",
    created_at: now.toISOString(),
    contacts: { id: "demo-1", display_name: "Jordan Lee", photo_url: null },
  },
  {
    id: "rem-2",
    user_id: "demo",
    type: "note_due",
    status: "pending",
    due_at: addDays(now, 2).toISOString(),
    title: "Remember for Jordan Lee",
    body: "Ask about the new apartment — they mentioned moving in September.",
    contact_id: "demo-1",
    note_id: "note-1",
    event_id: null,
    dedupe_key: "demo-note-1",
    created_at: now.toISOString(),
    contacts: { id: "demo-1", display_name: "Jordan Lee", photo_url: null },
  },
  {
    id: "rem-3",
    user_id: "demo",
    type: "birthday",
    status: "pending",
    due_at: addDays(now, 3).toISOString(),
    title: "Sam Rivera's birthday",
    body: "Wish Sam a happy birthday.",
    contact_id: "demo-2",
    note_id: null,
    event_id: null,
    dedupe_key: "demo-bday-1",
    created_at: now.toISOString(),
    contacts: { id: "demo-2", display_name: "Sam Rivera", photo_url: null },
  },
  {
    id: "rem-4",
    user_id: "demo",
    type: "anniversary",
    status: "pending",
    due_at: addDays(now, 10).toISOString(),
    title: "Sam Rivera's anniversary",
    body: "Remember Sam today.",
    contact_id: "demo-2",
    note_id: null,
    event_id: null,
    dedupe_key: "demo-ann-1",
    created_at: now.toISOString(),
    contacts: { id: "demo-2", display_name: "Sam Rivera", photo_url: null },
  },
];
